version: "3.8"

services:

  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db


  api:
    build:
      dockerfile: fastapi.Dockerfile
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - 8000:8000
    restart: "no"
    stdin_open: true
    tty: true
    depends_on:
      - mongodb

volumes:
  mongo: